This notebook introduces us with the **autograd** Torch package and the **torch.Tensor** class

In [1]:
import torch

### Tensor

In [2]:
# create a tensor and set 'requires_grad=True' to track computations
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


y was created as a result of an operation, so it has a **'grad_fn'**

In [4]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [5]:
a = torch.randn(2,2)
a = ((a * 3)/ a -1)
print("The input flag defaults to: " + str(a.requires_grad))
a.requires_grad_(True)
print("In-place flag change to: " + str(a.requires_grad))
b = (a * a).sum()
print(b.grad_fn)

The input flag defaults to: False
In-place flag change to: True


## Gradients
Let's backprog now

In [6]:
out.backward()

In [7]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


**torch.autograd** is an engine for computing Jacobian-vector product.

In [8]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([164.1372, 534.2402, 945.2969], grad_fn=<MulBackward>)


In [9]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([ 51.2000, 512.0000,   0.0512])


In [10]:
# stop autograd from tracking history on Tensors

print(x.requires_grad)
print((x **2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
