This notebook is aimed at introducing basic ideas of Pytorch

In [1]:
from __future__ import print_function
import torch

### Matrices

In [2]:
# 5x3 matrix
x = torch.empty(5,3)
print(x)

tensor([[-2.2923e+08,  4.5887e-41, -2.2923e+08],
        [ 4.5887e-41,  5.8337e-10,  1.3567e-19],
        [ 1.4584e-19,  7.8447e+17,  1.3556e-19],
        [ 1.3563e-19,  1.3563e-19,  1.8561e-19],
        [ 1.4584e-19,  2.4756e-12,  4.1411e-11]])


In [3]:
# randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.0057, 0.4290, 0.3098],
        [0.0444, 0.7383, 0.3480],
        [0.7775, 0.7142, 0.9894],
        [0.1600, 0.9330, 0.9321],
        [0.6851, 0.0506, 0.8549]])


In [4]:
# zero matrix of dtype long
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Tensors

In [7]:
# tensor constructed directly from data
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
# tensor constructed from another tensor
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9829, -1.3725,  0.3961],
        [-0.9292, -0.3133, -0.1786],
        [ 1.9233, -0.4905,  0.3177],
        [-1.0227, -0.3641, -0.1449],
        [ 0.4925, -0.5365,  0.0713]])


### Operations

**addition**

In [9]:
# syntax 1
y = torch.rand(5,3)
print(x + y)

tensor([[-0.0624, -0.6051,  0.6742],
        [-0.3215, -0.2146,  0.6412],
        [ 2.4085,  0.3489,  0.8124],
        [-0.7164,  0.2240,  0.6141],
        [ 1.2416, -0.1837,  0.5589]])


In [10]:
# syntax 2
print(torch.add(x,y))

tensor([[-0.0624, -0.6051,  0.6742],
        [-0.3215, -0.2146,  0.6412],
        [ 2.4085,  0.3489,  0.8124],
        [-0.7164,  0.2240,  0.6141],
        [ 1.2416, -0.1837,  0.5589]])


In [12]:
# providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x,y, out= result)
print(result)

tensor([[-0.0624, -0.6051,  0.6742],
        [-0.3215, -0.2146,  0.6412],
        [ 2.4085,  0.3489,  0.8124],
        [-0.7164,  0.2240,  0.6141],
        [ 1.2416, -0.1837,  0.5589]])


In [13]:
# in-place
y.add_(x)
print(y)

tensor([[-0.0624, -0.6051,  0.6742],
        [-0.3215, -0.2146,  0.6412],
        [ 2.4085,  0.3489,  0.8124],
        [-0.7164,  0.2240,  0.6141],
        [ 1.2416, -0.1837,  0.5589]])


**NumPy-like**

In [15]:
# indexing
print(x[:,1])

tensor([-1.3725, -0.3133, -0.4905, -0.3641, -0.5365])


In [16]:
# resizing
x = torch.randn(4,4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1,8) # the size -1 is inferred from other dimensions
print(z)

print(x.size(), y.size(), z.size())

tensor([[-0.4443, -0.3263, -0.9260,  0.6400],
        [ 0.2326,  0.6004,  1.1441,  1.8164],
        [ 0.4695,  0.9143, -1.1069,  0.5749],
        [ 0.7967, -0.6390, -1.4375,  0.7883]])
tensor([-0.4443, -0.3263, -0.9260,  0.6400,  0.2326,  0.6004,  1.1441,  1.8164,
         0.4695,  0.9143, -1.1069,  0.5749,  0.7967, -0.6390, -1.4375,  0.7883])
tensor([[-0.4443, -0.3263, -0.9260,  0.6400,  0.2326,  0.6004,  1.1441,  1.8164],
        [ 0.4695,  0.9143, -1.1069,  0.5749,  0.7967, -0.6390, -1.4375,  0.7883]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
# Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1827])
-0.1827099770307541


**NumPy bridge**

In [18]:
# from Torch Tensor to NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [20]:
# from NumPy Array to Torch Tensor
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**CUDA Tensors**

In [21]:
# We will use 'torch.device' objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")         # a CUDA device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device)                      # another way
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))      # .to can also change dtype together

tensor([0.8173], device='cuda:0')
tensor([0.8173], dtype=torch.float64)
